


services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql_pass
      POSTGRES_DB: postgres
  
  django:
    build:
      context: .
      dockerfile: Dockerfile
    # command: python manage.py test
    volumes:
      - .:/app
    environment:
      POSTGRESQL_HOST: postgres